//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGDIEMMON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANGDIEMMON()
        {
            this.CT_BANGDIEMMON = new HashSet<CT_BANGDIEMMON>();
            this.CT_BANGDIEMMON1 = new HashSet<CT_BANGDIEMMON>();
        }
    
        public int MABDM { get; set; }
        public Nullable<int> MAMH { get; set; }
        public Nullable<int> MAQTH { get; set; }
        public Nullable<double> DIEMTRUNGBINHMON { get; set; }
    
        public virtual QUATRINHHOC QUATRINHHOC { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BANGDIEMMON> CT_BANGDIEMMON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BANGDIEMMON> CT_BANGDIEMMON1 { get; set; }
        public virtual QUATRINHHOC QUATRINHHOC1 { get; set; }
    }
}
