//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUONGTRINHHOC
    {
        public int MACTH { get; set; }
        public Nullable<int> MAKHOI { get; set; }
        public Nullable<int> MAMH { get; set; }
        public Nullable<double> HESO { get; set; }
    
        public virtual KHOI KHOI { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
