//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCSINH()
        {
            this.QUATRINHHOCs = new HashSet<QUATRINHHOC>();
            this.QUATRINHHOCs1 = new HashSet<QUATRINHHOC>();
        }
    
        public int MAHS { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUATRINHHOC> QUATRINHHOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUATRINHHOC> QUATRINHHOCs1 { get; set; }
    }
}
