//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIHINHKIEMTRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIHINHKIEMTRA()
        {
            this.CT_BANGDIEMMON = new HashSet<CT_BANGDIEMMON>();
        }
    
        public int MALHKT { get; set; }
        public string TENLHKT { get; set; }
        public Nullable<double> HESODIEM { get; set; }
        public Nullable<int> THOIGIANKIEMTRA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BANGDIEMMON> CT_BANGDIEMMON { get; set; }
    }
}
