//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLHSEntities2 : DbContext
    {
        public QLHSEntities2()
            : base("name=QLHSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGDIEMMON> BANGDIEMMONs { get; set; }
        public virtual DbSet<CHUONGTRINHHOC> CHUONGTRINHHOCs { get; set; }
        public virtual DbSet<HOCKY> HOCKies { get; set; }
        public virtual DbSet<HOCSINH> HOCSINHs { get; set; }
        public virtual DbSet<KHOI> KHOIs { get; set; }
        public virtual DbSet<LOAIHINHKIEMTRA> LOAIHINHKIEMTRAs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<MONHOC> MONHOCs { get; set; }
        public virtual DbSet<QUATRINHHOC> QUATRINHHOCs { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
        public virtual DbSet<TONGKETHOCKY> TONGKETHOCKies { get; set; }
        public virtual DbSet<TONGKETMON> TONGKETMONs { get; set; }
        public virtual DbSet<CT_BANGDIEMMON> CT_BANGDIEMMON { get; set; }
    }
}
