//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUATRINHHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUATRINHHOC()
        {
            this.BANGDIEMMONs = new HashSet<BANGDIEMMON>();
            this.BANGDIEMMONs1 = new HashSet<BANGDIEMMON>();
        }
    
        public int MAQTH { get; set; }
        public Nullable<int> MALOP { get; set; }
        public Nullable<int> MAHS { get; set; }
        public Nullable<int> MAHK { get; set; }
        public Nullable<double> DIEMTB_HOCKY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGDIEMMON> BANGDIEMMONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGDIEMMON> BANGDIEMMONs1 { get; set; }
        public virtual HOCKY HOCKY { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual HOCSINH HOCSINH1 { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
